language: python
python:
  - "2.7"
  - "3.6"
before_install:
  - pip install --upgrade pip
  - pip install flake8
  - flake8 . --count --max-line-length=82 --statistics --exit-zero
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - nosetests
  - flake8 . --count --select=E999  # Stop build on syntax errors
